name: Build and deploy ASP.Net Core app to Azure Web App - webapplication-dotnet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Check Azure CLI version
        run: az --version

      - name: Install Azure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-cli

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./DEMO

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./DEMO

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Azure Login
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webapplication-dotnet'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_765982955AD64442ADCE11D82C6D385E }}

      - name: Debug Information
        run: |
          echo "AZURE_PUBLISH_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_765982955AD64442ADCE11D82C6D385E }}"
          echo "Web App URL: ${{ steps.deploy-to-webapp.outputs.webapp-url }}"
